version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: hh-archi-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hhplus1234
      MYSQL_DATABASE: hh-archi
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

volumes:
  mysql_data: